# Generated by Django 3.2 on 2021-04-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('device_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('horizon', models.FloatField()),
                ('vertical', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('video_addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fire.deviceinfo')),
            ],
        ),
    ]
