# Generated by Django 3.2 on 2021-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dealed',
            field=models.BooleanField(default=False),
        ),
    ]
