# Generated by Django 3.2 on 2021-05-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_message_dealed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='horizon',
        ),
        migrations.RemoveField(
            model_name='deviceinfo',
            name='vertical',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
