# Generated by Django 3.2 on 2021-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0004_alter_deviceinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
