# Generated by Django 3.2 on 2021-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0007_alter_deviceinfo_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='sensitive',
            field=models.IntegerField(default=1),
        ),
    ]
