# Generated by Django 3.2 on 2021-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0008_deviceinfo_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='sensitive',
            field=models.IntegerField(default=2),
        ),
    ]
